theme: minima
title: Alec is Awesome 
author: Alec Balemr
email: balmeralec13@gmail.com
description: > # this means to ignore newlines until "baseurl:"
this is to show off how awesome i am
# social links
twitter_username: N/A
github_username:  alec-balmer

show_excerpts: true # set to false to remove excerpts on the homepage
